---

- name: "Desplegar terraform apply {{ vm_name }}"
  cloud.terraform.terraform:
    project_path: '{{ terraform_project_dir }}/{{ vm_name }}'
    force_init: true
    state: "{{ vm_name_state }}"
