---
- name: Crear grupo iac
  ansible.builtin.group:
    name: terraformgroup
    state: present

- name: Crear usuario iac
  ansible.builtin.user:
    name: terraformuser
    group: terraformgroup
    ssh_key_file: setup_node0x/terraform_ed25519.pub

- name: Agregar llave SSH
  ansible.posix.authorized_key:
    user: terraformuser
    state: present
    key: "{{ lookup('file', 'terraform_ed25519.pub') }}"

- name: Crear directorio para entornos de iac
  ansible.builtin.file:
    path: "{{ terraform_project_dir }}"
    state: directory
    owner: terraformuser
    group: terraformgroup
    mode: "0664"
