- name: Configurar Nodos 0x
  hosts: aws__node0x
  gather_facts: true
  become: yes
  tasks:
    - name: Abtener facts de los servidores
      ansible.builtin.setup
    - name: Instalar paquetes para nodo ejecutor epel
      yum:
        name: "https://dl.fedoraproject.org/pub/epel/epel-release-latest-9.noarch.rpm"
        state: present
    - name: Instalar paquetes para nodo ejecutor ansible
      dnf:
        name: "{{ item }}"
        state: present
      loop:
        - ansible
