---

- name: Configurar Nodos 0x
  hosts: aws__node0x
  gather_facts: true
  become: true
  tasks:
    - name: Configurar ambiente de nodos
      tags:
        - preconfig-terraform
        - play-terraform
      block:
        - name: Configurar node terraform
          ansible.builtin.import_tasks: tasks/preconfig-terraform.yml

    - name: Crear templates de codigo para terraform
      tags:
        - template-terraform
        - play-terraform
      block:
        - name: "Crear templates de MV para terraform"
          ansible.builtin.include_tasks: tasks/template-terraform.yml
          vars:
            vm_name: "{{ vm_item }}"
          loop: "{{ aws_terraform_mv }}"
          loop_control:
            loop_var: vm_item

    - name: Desplegar infraestructura
      tags:
        - apply-terraform
        - play-terraform
      block:
        - name: Crear MV con terraform
          ansible.builtin.include_tasks: tasks/apply-terraform.yml
          vars:
            vm_name: "{{ vm_item }}"
          loop: "{{ aws_terraform_mv }}"
          loop_control:
            loop_var: vm_item

#export ANSIBLE_CONFIG="setup_node0x/ansible.cfg"