- name: Configurar Nodos 0x
  hosts: aws__node0x
  gather_facts: true
  become: yes
  tasks:
    - name: Agregar llaves
      rpm_key:
        state: present
        key: http://download.fedoraproject.org/pub/epel/RPM-GPG-KEY-EPEL-9
    - name: Agregar repositorios yum
      yum_repository:
        name: "{{ item.name }}"
        description: "{{ item.name }}"
        baseurl: "{{ item.baseurl }}"
        state: "{{ item.state }}"
      loop:
        - { name: epel, baseurl: "https://download.fedoraproject.org/pub/epel/$releasever/$basearch/" , state: abstent }
        - { name: terraform, baseurl: "https://rpm.releases.hashicorp.com/$release/hashicorp.repo",  state: present }

    - name: Instalar paquetes para nodo ejecutor ansible
      dnf:
        name: "{{ item }}"
        state: present
      loop:
        - epel
        - ansible
        - terraform

