---

- name: "Enviar mensaje a teams"
  hosts: "{{ ansible_apply_group | default('all') }}"
  become: false
  vars:
    role_webhook_endpoint: "{{ role_webhook_endpoint }}"
  roles:
    - carlos_zrm.teams_msg.webhook
