---
- name: Configurar Nodos
  hosts: "{{ ansible_apply_group | default('all') }}"
  gather_facts: true
  become: true
  tasks:
    - name: Configurar ambiente del nodo
      tags:
        - play-rhc
      block:
        - name: Configurar servidor
          ansible.builtin.import_tasks: tasks/config-rhel.yml

- name: "Registrar sistema"
  hosts: "{{ ansible_apply_group | default('all') }}"
  become: true
  vars:
    rhc_release: "{{ ansible_distribution_version }}"
    rhc_auth:
      login:
        username: "{{ rhn_username }}"
        password: "{{ rhn_password }}"
  roles:
    - redhat.rhel_system_roles.rhc