---
- name: Verifica si el contenedor existe
  hosts: "{{ ansible_apply_group | default('all') }}"
  become: true
  tasks:
    - name: Podman ps "{{ pod_name }}"
      ansible.builtin.shell: "podman ps --all --filter name={{ pod_name }}"
      register: podman_ps
    - name: Debug podman
      ansible.builtin.debug:
        msg: "{{ podman_ps }}"
      
- name: Configurar Nodos
  hosts: "{{ ansible_apply_group | default('all') }}"
  gather_facts: true
  become: true
  tasks:
    - name: Integracion continua del codigo
      tags:
        - play-git
      block:
        - name: Git PULL
          ansible.builtin.import_tasks: tasks/git-pull.yml

- name: Crear servidor WEB
  hosts: "{{ ansible_apply_group | default('all') }}"
  become: true
  tasks:
    - name: Despliegue continuo del codigo
      tags:
        - play-podman
      block:
        - name: Podman run
          ansible.builtin.import_tasks: tasks/config-podman.yml
