---

git_url: https://github.com/Carlos-ZRM/sitio-estatico.git
dir_www: /var/www/html

pod_name: ubi8-httpd

pod_image: "registry.access.redhat.com/ubi8/httpd-24:1-263.1684490927"
pod_state: started
#pod_state: absent

pod_ports:
  - containerPort: 8080
    hostPort: 8080

podman_firewall:
  - port: 8080/tcp
    state: enabled

podman_kube_specs:
  - state: "{{ pod_state }}"
    kube_file_content:
      apiVersion: v1
      kind: Pod
      metadata:
        name: "{{ pod_name }}"
      spec:
        containers:
          - name: "{{ pod_name }}"
            image: "{{ pod_image }}"
            ports:
              - containerPort: 8080
                hostPort: 8080
            volumeMounts:
                - mountPath: "{{ dir_www }}:Z"
                  name: "{{ pod_name }}-html"
        volumes:
          - name: "{{ pod_name }}-html"
            hostPath:
              path: "{{ dir_www }}"
            # volumes:
            #   - name: ubi8-html-vps
            #     persistentVolumeClaim:
            #       claimName: ubi8-html-volume

tags:
  name: carlosxpk
