---
- name: Playbook to get ETCD health
  hosts: localhost
  connection: local
  # module_defaults:
  #   redhat.openshift.openshift:
  #     kubeconfig: sa-kubeconfig
  collections:
    - tam.ocp
  tasks:
    - name: Get Status etcd
      ansible.builtin.import_role:
        name: ocp-etcd-health
      vars:
        defrag: true
