---
- name: Instalar paquetes para nodo ejecutor ansible
  ansible.builtin.dnf:
    name: "{{ item }}"
    state: present
  loop:
    - podman

- name: DNF update the system
  ansible.builtin.dnf:
    name:  podman
    state: latest
    update_only: true

- name: Ejecutar servidor
  become: true
  ansible.builtin.shell: "podman run --rm --name {{ pod_name }} -d -p 8080:8080 -v {{ dir_www }}/:{{ dir_www }}/:Z {{ pod_image }}"

# podman run -it --name httpd -p 8080:8080 -v /var/www/html/:/var/www/html:Z registry.access.redhat.com/ubi8/httpd-24
