---
- name: Instalar paquetes para nodo ejecutor ansible
  ansible.builtin.dnf:
    name: "{{ item }}"
    state: present
  loop:
    - podman

- name: ejecutar servidor
  become: true
  shell: "podman run --rm --name {{ pod_name }} -d -p 8080:8080 -v {{ dir_www }}/:{{ dir_www }}/:Z {{ pod_image }}"
