---

- name: Verificar si el contenedor existe
  become: true
  ansible.builtin.shell: "podman container exists {{ pod_name }}"
  register: podman_status


- name: Crear servidor servidor
  become: true
  ansible.builtin.shell: "podman run --rm --name {{ pod_name }} -d -p 8080:8080 -v {{ dir_www }}/:{{ dir_www }}/:Z {{ pod_image }}"

# podman run -it --name httpd -p 8080:8080 -v /var/www/html/:/var/www/html:Z registry.access.redhat.com/ubi8/httpd-24
