---


- name: "Agregar reglas de usuario acl al directorio {{ dir_www}}"
  ansible.posix.acl:
    path: "/var/www"
    entity: "{{ dir_www }}/"
    etype: user
    permissions: rwx
    state: present
    recursive: true
  

- name: Eliminar archivos anteriores
  ansible.builtin.file:
    path: "{{ dir_www }}/"
    mode: '0644'
    state: absent

- name: Cambiar permisos de directorio o crear direcotrio
  ansible.builtin.file:
    path: "{{ dir_www }}"
    mode: '0755'
    state: directory

- name: Git checkout
  ansible.builtin.git:
    repo: "{{ git_url }}"
    dest: "/tmp"
    force: true
  become: true
  become_user: "{{ crear_usuario | default('ansibleap-usuario') }}"
