---


- name: "Agregar reglas de usuario acl al directorio {{ dir_www}}"
  ansible.posix.acl:
    path: "{{ dir_www }}"
    entity: "{{ ansible_user }}"
    etype: user
    permissions: rwx
    state: present
    recursive: true
  
- name: Crear directorio temporal
  ansible.builtin.file:
    path: "/tmp{{ dir_www }}"
    mode: '0764'
    state: directory

- name: Eliminar archivos anteriores
  ansible.builtin.file:
    path: "{{ dir_www }}/"
    mode: '0644'
    state: absent

- name: Cambiar permisos de directorio o crear direcotrio
  ansible.builtin.file:
    path: "{{ dir_www }}"
    mode: '0755'
    state: directory

- name: Git checkout
  ansible.builtin.git:
    repo: "{{ git_url }}"
    dest: "/tmp{{ dir_www }}"
    force: true
  become: true
  become_user: "{{ crear_usuario | default('ansibleap-usuario') }}"

